[project]
name = "epconversions"
version = "0.2.2"
description = "Unit conversions for E+"
readme = "README.rst"
requires-python = ">=3.9,<3.10"
dependencies = []

[dependency-groups]
dev = [
    "coverage>=7.10.7",
    "pytest>=8.4.2",
    "sphinx-autodoc-typehints>=2.3.0",
    "sphinxcontrib-napoleon>=0.7",
]
